import turtle
# creating a turtle
t=turtle.Turtle()
# setting the speed of turtle to 1
t.speed(1)
# background color to black
turtle.bgcolor("black")
# Setting the pensize to 5
t.pensize(5)
# The pen will not work now here
t.penup()
# Changing the location of the turtle
t.goto(-330,280)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.forward(650)
t.right(90)
t.forward(150)
t.right(90)
t.forward(650)
t.right(90)
t.forward(150)
t.end_fill()
t.penup()
t.goto(-330,-40)
t.pendown()
t.fillcolor("green")
t.begin_fill()
t.right(90)
t.forward(650)
t.right(90)
t.forward(150)
t.right(90)
t.forward(650)
t.right(90)
t.forward(150)
t.end_fill()
t.fillcolor("white")
t.begin_fill()
t.right(90)
t.forward(650)
t.left(90)
t.forward(170)
t.left(90)
t.forward(650)
t.left(90)
t.forward(170)
t.end_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.left(90)
t.pencolor("blue")
t.circle(50)
t.penup()
t.goto(0,50)
t.pendown()
t.forward(50)
t.penup()
t.goto(0, 50)
t.pendown()
angle=15
for i in range(23):
    t.right(angle)
    t.forward(50)
    t.penup()
    t.goto(0,50)
    t.pendown()
t.hideturtle()
turtle.done()
